trigger:
  branches:
    include:
      - 'feature/*'
      - 'master'
  tags:
    include:
      - '*'

pool:
  vmImage: "ubuntu-latest"

variables:
  dockerRegistryServiceConnection: 'd46a8808-46ca-4d98-8cf4-ec41c18db25b'
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  isTag: $[startsWith(variables['Build.SourceBranch'], 'refs/tags/')]
  imageTag: dev
  environment: dev

jobs:
  - job: Build
    steps:
      - checkout: self
        fetchDepth: 3
        clean: true
      - script: "##vso[task.setvariable variable=environment]prod"
        displayName: Set the git tag name as environment variable
        condition: eq(variables.isTag, true)
      - script: VERSION_TAG=`git describe --tags` && echo "##vso[task.setvariable variable=imageTag]$VERSION_TAG"
        displayName: Set the git tag name as environment variable
        condition: eq(variables.isTag, true)
      - script: "##vso[task.setvariable variable=imageTag]latest"
        displayName: Set the git tag name as environment variable
        condition: eq(variables.isMaster, true)
      - script: VERSION_TAG=`git rev-parse --short HEAD` && echo "##vso[task.setvariable variable=imageTag]$VERSION_TAG"
        displayName: Set the git tag name as environment variable
        condition: and(eq(variables.isTag, false), eq(variables.isMaster, true))

      - task: Docker@2
        displayName: Build image to container registry
        inputs:
          command: buildAndPush
          repository: $(Build.SourcesDirectory)
          dockerfile: $(Build.SourcesDirectory)/Dockerfile
          containerRegistry: $( parameters.dockerRegistryServiceConnection )
          tags: |
            $( imageTag )
